server:
  port: 8888
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: koi-gateway
  config:
    import:
      - optional:nacos:${spring.application.name}.yaml
      - optional:nacos:redis.yaml
      - optional:classpath:gateway-swagger.yaml
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      username: nacos
      password: nacos
      discovery:
        server-addr: ${spring.cloud.nacos.server-addr}
        namespace: public
      config:
        server-addr: ${spring.cloud.nacos.server-addr}
        namespace: public
