knife4j:
  gateway:
    enabled: true
    strategy: manual
    routes:
      - name: Iam
        url: /iam/api-docs?group=default
        context-path: /iam
        service-name: koi-iam
        order: 1
      - name: Suite
        url: /suite/api-docs?group=default
        context-path: /suite
        service-name: koi-suite
        order: 2
      - name: Bpm
        url: /bpm/api-docs?group=default
        context-path: /bpm
        service-name: koi-bpm
        order: 3